/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability 
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2020 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
*  File Name    : G23_RSSK_0412.c
*  Description  : Main Program
*  Creation Date: 2025-04-12
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"
#include "Debug_UART/debug_uart.h"
#include <stdio.h>
#include "qe_touch_config.h"

extern void qe_touch_main(void);
int main (void);

/* 全局变量 */
volatile uint32_t g_msCounter = 0;  // 毫秒计数器

/* 定时器中断处理函数 */
void timer_interrupt_handler(void)
{
    g_msCounter++;
}

int main(void)
{
    fsp_err_t err;
    EI();
    R_Config_ITL000_ITL001_ITL012_ITL013_Start();
    R_Config_TAU0_1_Start();
    R_Config_UARTA1_Start();   // 启动UARTA1(示例)



    /* Initialize pins (function created by Smart Configurator) */
    R_CTSU_PinSetInit();


    /* Open Touch middleware */
    err = RM_TOUCH_Open (g_qe_touch_instance_config01.p_ctrl, g_qe_touch_instance_config01.p_cfg);
    if (FSP_SUCCESS != err)
    {
        while (true) {}
    }

    /* Debug库配置 */
    DebugConfig_t cfg = 
    {
        .tsFormat        = DEBUG_TS_MS,
        .minIntervalMs   = 0,  // 设置为0，不做时间间隔限制
        .maxProcessTimeUs= 1000,
        .bufferSize      = 128,
        .queueDepth      = 128,  // 示例: 与 bufferSize 相同
        .enableCRC       = false,
        .enableColor     = true
    };
    
    /* 初始化调试模块 */
    Debug_Init(&cfg);
    
    /* 打印启动消息 */
    Debug_Send("MAIN", DEBUG_COLOR_GREEN, __FILE__, __func__, __LINE__, "System started\r\n");
    
    /* 主循环状态 */
    uint32_t print_time = 0;
    uint32_t loop_count = 0;
    
    while(1)
    {
        /* 处理调试消息 - 非阻塞 */
        Debug_Process();
        
        /* 每隔1秒打印一次消息 */
        uint32_t now = g_msCounter;

            print_time = now;
            
            /* 打印示例消息 */
            // Debug_Send("MAIN", DEBUG_COLOR_YELLOW, __FILE__, __func__, __LINE__, 
            //           "Hello from main. Loop count: %lu\r\n", loop_count);
            // Debug_Send("MAIN", DEBUG_COLOR_CYAN, __FILE__, __func__, __LINE__, 
            //           "Hello from main 222. Time: %lu ms\r\n", now);
            
        
        /* 执行其他任务 */
        qe_touch_main();  // 触摸处理
        
        /* 增加循环计数 */
        loop_count++;
    }
}
